[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.20"

[features]
seeds = false
skip-lint = false

[programs.localnet]
bridge = "H3mPx8i41Zn4dLC6ZQRBzNRe1cqYdbcDP1WpojnaiAVo"
minter = "47pM7t6NrHmmrkrnnpr1FfVYNHCohVsStaAsdaqYsxEV"
rsol = "47pM7t6NrHmmrkrnnpr1FfVYNHCohVsStaAsdaqYsxEV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"
